---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: mytomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: mytomcat
    spec:
      containers:
      - name: mytomcat
        image: dockerdk194/mytomcat
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Service
metadata:
  name: nodeport-svc-demo
spec:
  type: NodePort
  selector:
    app: mytomcat
  ports:
  - name: demo-port
    protocol: TCP
    port: 80
    targetPort: 8080
