---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: mytomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: mytomcat
    spec:
      containers:
      - name: mytomcat
        image: dockerdk194/mytomcat
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
 name: tomcat-service
spec:
  type: LoadBalancer
  selector:
     app: mytomcat
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
